
  CREATE TABLE "HR"."JOB_HISTORY" 
   (	"EMPLOYEE_ID" NUMBER(6,0) CONSTRAINT "BIN$B22CQgo0QWOCMbKIdCFWtw==$0" NOT NULL ENABLE, 
	"START_DATE" DATE CONSTRAINT "BIN$QHSi84TLR0K32Ni9VAasFg==$0" NOT NULL ENABLE, 
	"END_DATE" DATE CONSTRAINT "BIN$+vVT+rXvS6ikn+a/cnsbBw==$0" NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) CONSTRAINT "BIN$1wl3BepPSzGzfOJTwuIhhA==$0" NOT NULL ENABLE, 
	"DEPARTMENT_ID" NUMBER(4,0), 
	 CONSTRAINT "BIN$4hhHghRUTwyLjob0BpPV4A==$0" CHECK (end_date > start_date) ENABLE, 
	 CONSTRAINT "BIN$7BlkueccTcSAiCCFSf7Psg==$0" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" 
 
