
  CREATE TABLE "HR"."TEILNEHMER_JN" 
   (	"TLNJN_ID" NUMBER NOT NULL ENABLE, 
	"TLNJN_TLN_ID" NUMBER NOT NULL ENABLE, 
	"TLNJN_TLN_NAME" VARCHAR2(20), 
	"TLNJN_TLN_GEBURTSTAG" DATE, 
	"TLNJN_TLN_GROESSE" NUMBER, 
	"TLNJN_AUSBILDUNG" "HR"."T_AUSBILDUNG" , 
	"TLNJN_VALID_FROM" TIMESTAMP (6), 
	"TLNJN_VALID_TO" TIMESTAMP (6), 
	"TLNJN_TYP" VARCHAR2(1), 
	 CONSTRAINT "TEILNEHMER_JN_PK" PRIMARY KEY ("TLNJN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "TLNJN_AUSBILDUNG" STORE AS "NT_TLNJN_AUSBILDUNG"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE
 
